# Generated by Django 4.0.3 on 2022-07-22 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('number_folder', models.CharField(max_length=250, verbose_name='Numero de Carpeta')),
            ],
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multipleapp.case')),
            ],
        ),
    ]
