# Generated by Django 4.0.3 on 2022-07-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
