# Generated by Django 4.0.3 on 2022-07-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipleapp', '0002_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='allimgess'),
        ),
    ]
