# Generated by Django 4.0.3 on 2022-07-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multipleapp', '0005_alter_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casefile',
            name='case',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='CaseFile',
        ),
    ]
